#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 35.175.112.132
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
