#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 18.233.66.119
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
